#!/usr/bin/env python3
# Generates a WMMA (cooperative matrix) version of an FSR 4.1.1 "residual block" model pass
# (passes 1, 2 and 12: 3x3 conv 16->16, 1x1 16->32 + ReLU, 1x1 32->16, residual add) from the
# pass as vkd3d-proton dumped it.  usage: gen_pass1.py <pass.spvasm> [wave 32|64] > out.comp
#
# The weights of these passes are constants inside AMD's shader (only the biases come from the
# weights buffer), so they are extracted here and written into the generated shader.
import re
import subprocess
import sys

src = sys.argv[1]
wave = int(sys.argv[2]) if len(sys.argv) > 2 else 32
pp = subprocess.run([sys.executable, __file__.rsplit('/', 1)[0] + '/pp.py', src],
                    capture_output=True, text=True, check=True).stdout.split('\n')

def die(msg):
    sys.exit('gen_pass1: ' + msg)

def num(tok):
    return int(tok, 0) & 0xffffffff

# Walk the pseudo-code: constant stores into local arrays, and the loops that consume them.
arrays = {}          # 'L47' -> {index: value}
alias = {}           # '%270' -> ('%268', 0): index = phi + offset
loops = []           # (dest array, dest offset, weight array, [16 words], [input ids])
block = []
for line in pp:
    m = re.match(r'\d+: (L\d+)\[(\d+)\] = (0x[0-9a-f]+|-?\d+)$', line)
    if m:
        arrays.setdefault(m[1], {})[int(m[2])] = num(m[3])
    if re.match(r'\d+: %\w+:$', line):
        block = []
    block.append(line)
    if 'LoopMerge' in line:
        dots = [re.search(r'sdot\((\S+), (\S+)\)', x) for x in block]
        dots = [d for d in dots if d]
        dest = [re.match(r'\d+: (L\d+)\[(%\w+)\] = ', x) for x in block]
        dest = [d for d in dest if d]
        if len(dots) != 4 or not dest:
            die('unexpected loop shape')
        off = None
        for x in block:
            a = re.match(r'\d+: ' + re.escape(dest[0][2]) + r' = %\w+ \+ (\d+)$', x)
            if a:
                off = int(a[1])
        if off is None:
            die('no destination offset')
        loops.append({'dst': dest[0][1], 'off': off, 'ins': [d[1] for d in dots], 'at': len(loops)})
        loops[-1]['pending'] = True
    # the continue block names the weight array
    m = re.match(r'\d+: %\w+ = (L\d+)\[%\w+\]$', line)
    if m and loops and loops[-1].get('pending') and m[1] != loops[-1]['dst']:
        loops[-1]['w'] = [arrays[m[1]][k] for k in range(16)]
        loops[-1]['pending'] = False

if len(loops) != 52:
    die(f'expected 52 loops, found {len(loops)}')
conv1, conv2, conv3 = loops[:36], loops[36:44], loops[44:]
text = '\n'.join(pp)
for needle in ('+ 3456', '+ 4096', '+ 4736', '30752 *', '+ 33273664', '>u 1919', '>u 1079', 'cbv[2]', '>>s 7', '>>s 8',
               '*f 0.015625', '*f 0.000244140625', '*f 64'):
    if needle not in text:
        die(f'pass does not match the expected structure: no "{needle}"')
bias = [int(x) for x in re.findall(r'= %\w+ \+ (3456|4096|4736|\d{4})$', text, re.M)]

# Matrices: A[oc][ic] row major, 4 words per output channel.  Order: conv1 taps 0..8, conv2 a/b, conv3 a/b.
mats = [[0] * 64 for _ in range(13)]
seen = set()
for i, l in enumerate(conv1):
    g, tap = i // 9, i % 9
    if l['off'] != 4 * g:
        die('conv1 loop order')
    for oc in range(4):
        for k in range(4):
            mats[tap][(4 * g + oc) * 4 + k] = l['w'][4 * oc + k]
for i, l in enumerate(conv2):
    if l['off'] != 4 * i:
        die('conv2 loop order')
    for oc in range(4):
        for k in range(4):
            mats[9 + i // 4][((4 * i + oc) % 16) * 4 + k] = l['w'][4 * oc + k]
first_half = conv3[0]['ins']
for i, l in enumerate(conv3):
    g, half = i // 2, 0 if l['ins'] == first_half else 1
    if l['off'] != 4 * g or half != i % 2:
        die('conv3 loop order')
    for oc in range(4):
        for k in range(4):
            mats[11 + half][(4 * g + oc) * 4 + k] = l['w'][4 * oc + k]

ch = 256 // wave            # accumulator elements (channels) each invocation handles
words = ch // 4
consts = ',\n    '.join(', '.join(f'0x{v:08x}u' for v in m[i:i + 8]) for m in mats for i in range(0, 64, 8))

print(f'''#version 460
// Generated by gen_pass1.py from {src.rsplit('/', 1)[-1]}: the pass with its three convolutions done by WMMA
// (cooperative matrices, int8 x int8 -> int32) instead of packed dot products.
// One workgroup = one wave of {wave} = 64 pixels of a tensor row, in four tiles of 16 pixels.
//   A = weights [output channel][input channel] (from workgroup memory, filled from the constants),
//   B = pixels as columns (16 bytes per pixel), C = [output channel][pixel].
#extension GL_KHR_cooperative_matrix : require
#extension GL_KHR_memory_scope_semantics : require
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_buffer_reference_uvec2 : require
layout(local_size_x = {wave}) in;
layout(buffer_reference, std430, buffer_reference_align = 16) readonly buffer Sizes {{ uvec4 v[4096]; }};
layout(push_constant) uniform Root {{ uvec2 cbv; uint uav; uint srv; }} reg;
layout(set = 2, binding = 0) buffer Tensor {{ uint d[]; }} heap[];
layout(set = 2, binding = 0) readonly buffer Weights {{ uint d[]; }} wheap[];

#define ACC coopmat<int32_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseAccumulator>
#define MATA coopmat<int8_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseA>
#define MATB coopmat<int8_t, gl_ScopeSubgroup, 16, 16, gl_MatrixUseB>
const uint CH = {ch}u, WORDS = {words}u;

const uint weights[13 * 64] = uint[](
    {consts});

shared uint s_w[13 * 64];      // the 13 weight matrices
shared int s_acc[2 * 256];     // accumulators as [pixel][channel]
shared uint s_b[2 * 64];       // activations for the next layer, 16 bytes per pixel

int pack4(ivec4 v) {{
    v = clamp(v, ivec4(-128), ivec4(127)) & 0xff;
    return v.x | (v.y << 8) | (v.z << 16) | (v.w << 24);
}}

void main() {{
    const uint idx = gl_LocalInvocationIndex, px = idx & 15u, c0 = (idx >> 4) * CH;
    const uint y = gl_WorkGroupID.y, x0 = gl_WorkGroupID.x * 64u;
    const uint tensor = reg.uav + 11u, wbuf = reg.srv + 18u;
#ifndef NOINIT
    for (uint m = 0u; m < 13u; m++)
        for (uint k = idx; k < 64u; k += {wave}u)
            s_w[m * 64u + k] = weights[m * 64u + k];
#endif
    int b1[{ch}], b2a[{ch}], b2b[{ch}], b3[{ch}];
    for (uint j = 0u; j < CH; j++) {{
        b1[j] = int(wheap[wbuf].d[864u + c0 + j]);
        b2a[j] = int(wheap[wbuf].d[1024u + c0 + j]);
        b2b[j] = int(wheap[wbuf].d[1040u + c0 + j]);
        b3[j] = int(wheap[wbuf].d[1184u + c0 + j]);
    }}
    const uvec2 size = Sizes(reg.cbv).v[2].xy;
    barrier();
    MATA a[13];
    for (uint m = 0u; m < 13u; m++)
        coopMatLoad(a[m], s_w, m * 64u, 4u, gl_CooperativeMatrixLayoutRowMajor);

    for (uint tile = 0u; tile < 4u; tile++) {{
        const uint x = x0 + tile * 16u + px;
        // 3x3, 16 -> 16
        ACC acc = ACC(0);
        for (uint tap = 0u; tap < 9u; tap++) {{
            MATB b;
            coopMatLoad(b, heap[tensor].d, ((y + tap / 3u) * 1922u + x0 + tile * 16u + tap % 3u) * 4u, 4u, gl_CooperativeMatrixLayoutColumnMajor);
            acc = coopMatMulAdd(a[tap], b, acc);
        }}
        coopMatStore(acc, s_acc, 0u, 16u, gl_CooperativeMatrixLayoutColumnMajor);
        barrier();
#if defined(LEVEL) && LEVEL < 2
        continue;
#endif
        for (uint w = 0u; w < WORDS; w++) {{
            ivec4 v;
            for (uint j = 0u; j < 4u; j++) {{
                int t = s_acc[px * 16u + c0 + w * 4u + j] + b1[w * 4u + j];
                v[j] = (t + 63 + ((t >> 7) & 1)) >> 7;
            }}
            s_b[px * 4u + c0 / 4u + w] = uint(pack4(v));
        }}
        barrier();
#if defined(LEVEL) && LEVEL < 3
        continue;
#endif
        // 1x1, 16 -> 32, ReLU
        MATB h;
        coopMatLoad(h, s_b, 0u, 4u, gl_CooperativeMatrixLayoutColumnMajor);
        ACC acc2a = coopMatMulAdd(a[9], h, ACC(0)), acc2b = coopMatMulAdd(a[10], h, ACC(0));
        coopMatStore(acc2a, s_acc, 0u, 16u, gl_CooperativeMatrixLayoutColumnMajor);
        coopMatStore(acc2b, s_acc, 256u, 16u, gl_CooperativeMatrixLayoutColumnMajor);
        barrier();
#if defined(LEVEL) && LEVEL < 4
        continue;
#endif
        for (uint w = 0u; w < WORDS; w++) {{
            ivec4 va, vb;
            for (uint j = 0u; j < 4u; j++) {{
                int ta = max(s_acc[px * 16u + c0 + w * 4u + j] + b2a[w * 4u + j], 0);
                int tb = max(s_acc[256u + px * 16u + c0 + w * 4u + j] + b2b[w * 4u + j], 0);
                va[j] = (ta + 127 + ((ta >> 8) & 1)) >> 8;
                vb[j] = (tb + 127 + ((tb >> 8) & 1)) >> 8;
            }}
            s_b[px * 4u + c0 / 4u + w] = uint(pack4(va));
            s_b[64u + px * 4u + c0 / 4u + w] = uint(pack4(vb));
        }}
        barrier();
#if defined(LEVEL) && LEVEL < 5
        continue;
#endif
        // 1x1, 32 -> 16
        MATB ha, hb;
        coopMatLoad(ha, s_b, 0u, 4u, gl_CooperativeMatrixLayoutColumnMajor);
        coopMatLoad(hb, s_b, 64u, 4u, gl_CooperativeMatrixLayoutColumnMajor);
        ACC acc3 = coopMatMulAdd(a[11], ha, ACC(0));
        acc3 = coopMatMulAdd(a[12], hb, acc3);
        coopMatStore(acc3, s_acc, 0u, 16u, gl_CooperativeMatrixLayoutColumnMajor);
        barrier();
#if defined(LEVEL) && LEVEL < 6
        continue;
#endif
        // residual: input (scale 1/64) + result (scale 1/4096), back to scale 1/64
        const uint center = ((y + 1u) * 1922u + x + 1u) * 4u + c0 / 4u;
        const bool inside = x < size.x && y < size.y && x <= 1919u && y <= 1079u;
        for (uint w = 0u; w < WORDS; w++) {{
            const uint in_word = heap[tensor].d[center + w];
            ivec4 v;
            for (uint j = 0u; j < 4u; j++) {{
                const int t = s_acc[px * 16u + c0 + w * 4u + j] + b3[w * 4u + j];
                const int i = (int(in_word) << (24 - 8 * int(j))) >> 24;
                const float f = (float(i) * 0.015625 + float(t) * 0.000244140625) * 64.0;
                v[j] = (int(roundEven(f)) << 16) >> 16;
            }}
            if (inside)
                heap[tensor].d[(33273664u >> 2) + center + w] = uint(pack4(v));
        }}
        barrier();
    }}
}}''')
